/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_ysr_face_util_NdkUtil */

#ifndef _Included_com_app_ysr_face_util_NdkUtil
#define _Included_com_app_ysr_face_util_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_ysr_face_util_NdkUtil
 * Method:    getCmpPic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_app_ysr_face_util_NdkUtil_getCmpPic
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
